version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: webpack-sources
    versions:
    - 2.2.0
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: lodash
    versions:
    - 4.17.21
